---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# shape file

```{r}
library(sf)
library(tidyverse)
# map <- read_sf("../../data_raw/stanford-xg218hn4313-shapefile/xg218hn4313.shp") ## this was the old one, now we use another one
map <- read_sf("../../data_raw/shape/bol_adm_mdrt_2013/bol_admbnd_adm2_mdrt_2013_v01.shp") ## adm 2 because we dont use the municipalities anymore, but the provinces 

map$count <- 1:nrow(map)

ggplot(map) +
  geom_sf(aes(fill = count), color = "grey20", size = 0.1) +
  theme_classic()

```

# DHS data

Originally one of the topic Ideas was to use this dataset.

```{r}
library(haven)
dat_houshold_raw <- read_dta("../../data_raw/2008_DHS/BOHR51DT/BOHR51FL.DTA")
dim(dat_houshold_raw)
dat_houshold_raw[1:10,] %>% head(3)
```

# census 2024

This is the bolivian census from 2024

```{r}
# census <- read_csv("../../data_raw/large_files/Persona_CPV-2024.csv")

library(data.table)
# dat_census_person <- fread("../../data_raw/large_files/Persona_CPV-2024.csv") ### full census person
dat_census_person <- fread("../../data_raw/large_files/Persona_CPV-2024.csv", nrows = 100) ### only selection of first 100 rows

# dat_census_houshold <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv") ### full census houshold
dat_census_houshold <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv", nrows = 100) ### full census houshold

dat_census_person %>% colnames()
```


# houshold_survey 2021

This is the houshold_survey from 2021, also not part of the project anymore 

```{r}
library(haven)

dat_houshold_survey <- read_sav("../../data_raw/2021_houshold-survey/EH2021_Persona.sav")

## to create table for colnames and labels
var_info <- data.frame(
  variable = names(dat_houshold_survey),
  label = sapply(dat_houshold_survey, function(x) attr(x, "label")),
  row.names = NULL
)

var_info %>% head(10)
write_csv(var_info,file = "../../data_raw/2021_houshold-survey/doc/person_var_info.csv")
```

```{r}
### varaioble which housholds are in the same neighbourhood, but not possible to identify province 
# dat_houshold_survey$upm 
```

how many pers houshold per area?

```{r}
dat_houshold_survey %>% 
  mutate(depto = as_factor(depto)) %>% 
  group_by(depto) %>% count()
```