---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(reactable)
library(sf)
library(data.table)
library(saeTrafo)
library(emdi)
remove(list = ls())
```


## Adding an RMarkdown Template

```{r}
# ### load data
# dat_census_person <- fread("../../data_raw/large_files/Persona_CPV-2024.csv")
# 
# ### select variables
# dat_census_person <- dat_census_person %>% select(idep,iprov,imun,i00,aestudio,p25_sexo,p26_edad,p40_lee,ocu_1d_13)
# 
# ### only above 18
# dat_census_person <- dat_census_person %>% filter(p26_edad >= 18)
# 
# ### save as RDS
# saveRDS(dat_census_person,"../../data_raw/large_files/dat_census_person_selection_01.RDS")
```

```{r}
# dat_census_person <- readRDS("../../data_raw/large_files/dat_census_person_selection_01.RDS")
# 
# ### create IDs
# ### create ID for municipality
# dat_census_person$ID_mun <- paste0("BO",
#   sprintf("%02.0f", dat_census_person$idep),
#   sprintf("%02.0f", dat_census_person$iprov),
#   sprintf("%02.0f", dat_census_person$imun))
# 
# ### create ID for Province
# dat_census_person$ID_prov <- paste0("BO",
#   sprintf("%02.0f", dat_census_person$idep),
#   sprintf("%02.0f", dat_census_person$iprov))
# 
# saveRDS(dat_census_person,"../../data_raw/large_files/dat_census_person_selection_01.RDS")
```

### houshold data frame

```{r}
# dat_census_houshold <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv")
# 
# ### select variables
# dat_census_houshold <- dat_census_houshold %>% select(i00,v19c_compu,v10_combus,v06_piso,v19e_f,urbrur)
# 
# dat_census <- merge(dat_census_person,dat_census_houshold, by = "i00" )
# 
# saveRDS(dat_census_houshold,"../../data_raw/large_files/dat_census_houshold_selection_01.RDS")
# saveRDS(dat_census,"../../data_raw/large_files/dat_census_selection_01.RDS")
```


## sample 
```{r}
dat_census <- readRDS("../../data_raw/large_files/dat_census_selection_01.RDS")
```


```{r}
sample_size <- 20

set.seed(420)
sample <- dat_census %>%
  group_by(ID_prov) %>%
  slice_sample(n = sample_size) %>%
  ungroup()

unique(sample$ID_prov)
unique(sample$ID_prov) %>% length()
```

```{r}
# library(sf)
# map <- read_sf("../../data_raw/shape/bol_adm_mdrt_2013/bol_admbnd_adm2_mdrt_2013_v01.shp")
# map$ADM2_PCODE %>% length()
# 
# map$ADM2_PCODE %in% unique(sample$ID_prov) %>% table()
```

```{r}
direct_estimates <- sample %>%
  group_by(ID_prov) %>% 
  summarise(
    Mean     = mean(aestudio, na.rm = TRUE), 
    n_eff    = sum(!is.na(aestudio)), 
    Var_Mean = var(aestudio, na.rm = T)/n_eff,
    .groups  = "drop"
  )
```


```{r}
combined_data <- direct_estimates
combined_data <- combined_data %>% as.data.frame()
```

### aux data erstellen 
convert: v19c_compu,v10_combus,v06_piso,v19e_f,urbrur

```{r}
domain_cov_raw <-  dat_census %>% mutate(
  p25_sexo_t = case_when(
    p25_sexo %in% 1 ~ 1, ### 1 is female
    p25_sexo %in% 2 ~ 0), ### 2 was and 0 ist male now

  p40_lee_t = case_when(
    p40_lee %in% 1 ~ 1, ## 1 is knowing how to read
    p40_lee %in% 2 ~ 0), ## 2 was and 0 is not knowing how to read

  urb_t = case_when(
    urbrur %in% 1 ~ 1, ## 1 is urban
    urbrur %in% 2 ~ 0), ## 2 was and 0 is rural (not_urban)

  v19c_compu_t = case_when(
    v19c_compu %in% 1 ~ 1, ## 1 exists
    v19c_compu %in% 2 ~ 0, ## 2 was and 0 does not exist
    v19c_compu %in% 9 ~ NA), ## 9 is not specified -- we will set it to NA

  v10_combus_high_SES = case_when(
    v10_combus %in% c(2,5) ~ 1, ## 2 electricity or 5 gas through pipes
    !(v10_combus %in% c(2,5)) ~ 0),

  v10_combus_transitional_energy = case_when(
    v10_combus %in% c(1,6) ~ 1, ## 1 -  gas in cylinder 6 - solar energy
    !(v10_combus %in% c(1,6)) ~ 0),

  v10_combus_LOW_SES = case_when(
    v10_combus %in% c(3,4) ~ 1, ## 3fire wood dung, 4 agricultural residual as fuel
    !(v10_combus %in% c(3,4)) ~ 0), ## 1 exists

  v10_combus_other= case_when(
    v10_combus %in% c(7,8) ~ 1, ##  7 other, 8 no cooking place
    !(v10_combus %in% c(7,8)) ~ 0), ## 1 exists

  v19e_f_t = case_when(
    v19e_f %in% 1 ~ 1, ## 1 internet exist at home
    v19e_f %in% 2 ~ 0, ## does not exist
    v19e_f %in% 9 ~ NA), ## 9 is not specified -- we will set it to NA
  ocu_military = case_when(
    ocu_1d_13 %in% 0 ~ 1,
    !(ocu_1d_13 %in% 0) ~ 0),

  ocu_managers = case_when(
    ocu_1d_13 %in% 1 ~ 1,
    !(ocu_1d_13 %in% 1) ~ 0),

  ocu_professionals = case_when(
    ocu_1d_13 %in% 2 ~ 1,
    !(ocu_1d_13 %in% 2) ~ 0),

  ocu_technicians = case_when(
    ocu_1d_13 %in% 3 ~ 1,
    !(ocu_1d_13 %in% 3) ~ 0),

  ocu_adminSupport = case_when(
    ocu_1d_13 %in% 4 ~ 1,
    !(ocu_1d_13 %in% 4) ~ 0),

  ocu_serviceSales = case_when(
    ocu_1d_13 %in% 5 ~ 1,
    !(ocu_1d_13 %in% 5) ~ 0),

  ocu_agriculture = case_when(
    ocu_1d_13 %in% 6 ~ 1,
    !(ocu_1d_13 %in% 6) ~ 0),

  ocu_construction = case_when(
    ocu_1d_13 %in% 7 ~ 1,
    !(ocu_1d_13 %in% 7) ~ 0),

  ocu_operators = case_when(
    ocu_1d_13 %in% 8 ~ 1,
    !(ocu_1d_13 %in% 8) ~ 0),

  ocu_unskilled = case_when(
    ocu_1d_13 %in% 9 ~ 1,
    !(ocu_1d_13 %in% 9) ~ 0),

  ocu_incomplete = case_when(
    ocu_1d_13 %in% 97 ~ 1,
    !(ocu_1d_13 %in% 97) ~ 0),

  ocu_unspecified = case_when(
    ocu_1d_13 %in% 99 ~ 1,
    !(ocu_1d_13 %in% 99) ~ 0)
)

# which("urb_t" ==  colnames(domain_cov_raw)) ## 19
# colnames(domain_cov_raw)[19:37]

covariats_numeric <-c("p26_edad")

covariats_factors <- c(
  "p25_sexo_t",
  "p40_lee_t",
  "ocu_military",
  "ocu_managers",
  "ocu_professionals",
  "ocu_technicians",
  "ocu_adminSupport",
  "ocu_serviceSales",
  "ocu_agriculture",
  "ocu_construction",
  "ocu_operators",
  "ocu_unskilled",
  "ocu_incomplete",
  "ocu_unspecified",
  "urb_t",
  "v19c_compu_t",
  "v10_combus_high_SES",
  "v10_combus_transitional_energy",
  "v10_combus_LOW_SES",
  "v10_combus_other",
  "v19e_f_t"
)

census_aux_data <- domain_cov_raw %>%
  group_by(ID_prov) %>%
  summarise(
    across(all_of(covariats_numeric), ~ mean(.x, na.rm = TRUE), .names = "mean_{.col}"),
    across(all_of(covariats_factors), ~ mean(.x == 1, na.rm = TRUE), .names = "share_{.col}")
  ) %>%
  ungroup()

saveRDS(census_aux_data,"../../data_raw/2024_census/processed/census_aux_data_aggregated.RDS")
```

## lm with all covariats

```{r}
domain_cov_sample_raw <-  sample %>% mutate(
  p25_sexo_t = case_when(
    p25_sexo %in% 1 ~ 1, ### 1 is female
    p25_sexo %in% 2 ~ 0), ### 2 was and 0 ist male now

  p40_lee_t = case_when(
    p40_lee %in% 1 ~ 1, ## 1 is knowing how to read
    p40_lee %in% 2 ~ 0), ## 2 was and 0 is not knowing how to read

  urb_t = case_when(
    urbrur %in% 1 ~ 1, ## 1 is urban
    urbrur %in% 2 ~ 0), ## 2 was and 0 is rural (not_urban)

  v19c_compu_t = case_when(
    v19c_compu %in% 1 ~ 1, ## 1 exists
    v19c_compu %in% 2 ~ 0, ## 2 was and 0 does not exist
    v19c_compu %in% 9 ~ NA), ## 9 is not specified -- we will set it to NA

  v10_combus_high_SES = case_when(
    v10_combus %in% c(2,5) ~ 1, ## 2 electricity or 5 gas through pipes
    !(v10_combus %in% c(2,5)) ~ 0),

  v10_combus_transitional_energy = case_when(
    v10_combus %in% c(1,6) ~ 1, ## 1 -  gas in cylinder 6 - solar energy
    !(v10_combus %in% c(1,6)) ~ 0),

  v10_combus_LOW_SES = case_when(
    v10_combus %in% c(3,4) ~ 1, ## 3fire wood dung, 4 agricultural residual as fuel
    !(v10_combus %in% c(3,4)) ~ 0), ## 1 exists

  v10_combus_other= case_when(
    v10_combus %in% c(7,8) ~ 1, ##  7 other, 8 no cooking place
    !(v10_combus %in% c(7,8)) ~ 0), ## 1 exists

  v19e_f_t = case_when(
    v19e_f %in% 1 ~ 1, ## 1 internet exist at home
    v19e_f %in% 2 ~ 0, ## does not exist
    v19e_f %in% 9 ~ NA), ## 9 is not specified -- we will set it to NA
  ocu_military = case_when(
    ocu_1d_13 %in% 0 ~ 1,
    !(ocu_1d_13 %in% 0) ~ 0),

  ocu_managers = case_when(
    ocu_1d_13 %in% 1 ~ 1,
    !(ocu_1d_13 %in% 1) ~ 0),

  ocu_professionals = case_when(
    ocu_1d_13 %in% 2 ~ 1,
    !(ocu_1d_13 %in% 2) ~ 0),

  ocu_technicians = case_when(
    ocu_1d_13 %in% 3 ~ 1,
    !(ocu_1d_13 %in% 3) ~ 0),

  ocu_adminSupport = case_when(
    ocu_1d_13 %in% 4 ~ 1,
    !(ocu_1d_13 %in% 4) ~ 0),

  ocu_serviceSales = case_when(
    ocu_1d_13 %in% 5 ~ 1,
    !(ocu_1d_13 %in% 5) ~ 0),

  ocu_agriculture = case_when(
    ocu_1d_13 %in% 6 ~ 1,
    !(ocu_1d_13 %in% 6) ~ 0),

  ocu_construction = case_when(
    ocu_1d_13 %in% 7 ~ 1,
    !(ocu_1d_13 %in% 7) ~ 0),

  ocu_operators = case_when(
    ocu_1d_13 %in% 8 ~ 1,
    !(ocu_1d_13 %in% 8) ~ 0),

  ocu_unskilled = case_when(
    ocu_1d_13 %in% 9 ~ 1,
    !(ocu_1d_13 %in% 9) ~ 0),

  ocu_incomplete = case_when(
    ocu_1d_13 %in% 97 ~ 1,
    !(ocu_1d_13 %in% 97) ~ 0),

  ocu_unspecified = case_when(
    ocu_1d_13 %in% 99 ~ 1,
    !(ocu_1d_13 %in% 99) ~ 0)
)

# paste(covariats_factors,collapse = " + ")
### plus adding age variable 


model <- lm(data = domain_cov_sample_raw,
   formula = aestudio ~ p26_edad + p25_sexo_t + p40_lee_t + ocu_military + ocu_managers + ocu_professionals + ocu_technicians + ocu_adminSupport + ocu_serviceSales + ocu_agriculture + ocu_construction + ocu_operators + ocu_unskilled + ocu_incomplete + ocu_unspecified + urb_t + v19c_compu_t + v10_combus_high_SES + v10_combus_transitional_energy + v10_combus_LOW_SES + v10_combus_other + v19e_f_t) 

step(direction = "backward",object = model)

lm(formula = aestudio ~ p26_edad + p25_sexo_t + p40_lee_t + ocu_managers + 
    ocu_professionals + ocu_technicians + ocu_adminSupport + 
    ocu_agriculture + ocu_construction + ocu_incomplete + v19c_compu_t + 
    v10_combus_high_SES + v10_combus_LOW_SES, data = domain_cov_sample_raw) %>% summary()

lm(formula = aestudio ~ p26_edad + p25_sexo_t + p40_lee_t + ocu_managers + 
    ocu_professionals + ocu_technicians + ocu_adminSupport + 
    ocu_agriculture + v19c_compu_t + 
    v10_combus_high_SES + v10_combus_LOW_SES, data = domain_cov_sample_raw) %>% summary()

```

## FH models

### null model

```{r}
fh_model_null <- fh(
fixed = Mean ~ 1,
vardir = "Var_Mean",
combined_data = combined_data,
domains = "ID_prov",
method = "reml",
MSE = TRUE
)

fh_model_null$MSE$FH %>% mean()
```

### simple model

```{r}
### merge data together
census_aux_data_aggregated <- readRDS("../../data_raw/2024_census/processed/census_aux_data_aggregated.RDS")
combined_data <- merge(combined_data,census_aux_data_aggregated,by = "ID_prov")
```


```{r}
fh_model_simple <- fh(
  fixed = Mean ~ mean_p26_edad + share_p25_sexo_t,
  vardir = "Var_Mean",
  combined_data = combined_data,
  domains = "ID_prov",
  method = "reml",
  MSE = TRUE
)

fh_model_simple$MSE$FH %>% mean()
```

### complex model

```{r}
fh_model_complex <- fh(
  fixed = Mean ~ mean_p26_edad + share_p25_sexo_t + share_p40_lee_t + share_ocu_managers + 
    share_ocu_professionals + share_ocu_technicians + share_ocu_adminSupport + 
    share_ocu_agriculture + share_v19c_compu_t + 
    share_v10_combus_high_SES + share_v10_combus_LOW_SES,
  vardir = "Var_Mean",
  combined_data = combined_data,
  domains = "ID_prov",
  method = "reml",
  MSE = T
)

fh_model_complex$MSE$FH %>% mean()
```

# BHF

```{r}
freq <- dat_census %>% group_by(ID_prov) %>% count()
# freq %>% reactable(.,filterable = T)

freq_sample <- sample %>% group_by(ID_prov) %>% count()
# freq_sample %>% reactable(.,filterable = T)
```


```{r}
### create vector with sizo of domains
table_pop_size <- dat_census %>% group_by(ID_prov) %>% count()
vec_pop_size <- table_pop_size$n
names(vec_pop_size) <- table_pop_size$ID_prov

dat_BHF_census <- domain_cov_raw[!is.na(domain_cov_raw$aestudio),]
dat_BHF_census <- na.omit(dat_BHF_census)
dat_BHF_census$ID_prov <- dat_BHF_census$ID_prov %>% as.factor()
sapply(dat_BHF_census,FUN = function(x) sum(is.na(x)))

dat_BHF_sample <- domain_cov_sample_raw[!is.na(domain_cov_sample_raw$aestudio),]
dat_BHF_sample <- na.omit(dat_BHF_sample)
dat_BHF_sample$ID_prov <- dat_BHF_sample$ID_prov %>% as.factor()
sapply(dat_BHF_sample,FUN = function(x) sum(is.na(x)))
```

### BHF model simple

```{r}
domain_cov_raw

#### restrict data sets only to absolut necessary
vec_sample_variables <- c("ID_prov","p26_edad","p25_sexo_t","aestudio") 
vec_census_variables <- c("ID_prov","p26_edad","p25_sexo_t") 

dat_BHF_sample_selection <- dat_BHF_sample %>% select(vec_sample_variables)
dat_BHF_census_selection <- dat_BHF_census %>% select(vec_census_variables)

BHF_model_simple <-  NER_Trafo(fixed = aestudio ~ p26_edad + p25_sexo_t
    ,MSE = T
    ,smp_domains = "ID_prov"
    ,smp_data = dat_BHF_sample_selection
    ,pop_data = dat_BHF_census_selection
    ,pop_area_size = vec_pop_size
    ,pop_domains = "ID_prov"
    ,transformation = "no"
    ,seed = 2022)

BHF_model_simple$MSE$Mean %>% mean()
```

### BHF model complex

```{r}
vec_sample_variables <- c(
  "aestudio",
  "p26_edad",
  "ID_prov",
  "p25_sexo_t",
  "p40_lee_t",
  "ocu_managers",
  "ocu_professionals",
  "ocu_technicians",
  "ocu_adminSupport",
  "ocu_agriculture",
  "v19c_compu_t",
  "v10_combus_high_SES",
  "v10_combus_LOW_SES")

vec_census_variables <- c(
  "p26_edad",
  "ID_prov",
  "p25_sexo_t",
  "p40_lee_t",
  "ocu_managers",
  "ocu_professionals",
  "ocu_technicians",
  "ocu_adminSupport",
  "ocu_agriculture",
  "v19c_compu_t",
  "v10_combus_high_SES",
  "v10_combus_LOW_SES")

dat_BHF_sample_selection <- dat_BHF_sample %>% select(vec_sample_variables)
dat_BHF_census_selection <- dat_BHF_census %>% select(vec_census_variables)

BHF_model_complex <-  NER_Trafo(fixed = aestudio ~ p26_edad + p25_sexo_t + p40_lee_t + ocu_managers + 
    ocu_professionals + ocu_technicians + ocu_adminSupport + 
    ocu_agriculture + v19c_compu_t + 
    v10_combus_high_SES + v10_combus_LOW_SES
    ,smp_domains = "ID_prov"
    ,smp_data = dat_BHF_sample_selection
    ,pop_data = dat_BHF_census_selection
    ,pop_area_size = vec_pop_size
    ,pop_domains = "ID_prov"
    ,transformation = "no"
    ,seed = 2022
    ,MSE = T)

BHF_model_complex$MSE$Mean %>% mean()

```

