---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(reactable)
library(sf)
library(data.table)
remove(list = ls())
```

```{r}
sample <- readRDS("../../data_raw/samples/sample_for_model_building.RDS")
```

# selection

## filter for NAs
filter for variables which have lots of NAs 

```{r}
dat_table_nas <- sapply(sample, FUN = function(x) mean(is.na(x)))

dat_table_nas <- data.frame("name" = names(dat_table_nas),
           "percentage_na" = dat_table_nas)

nrow(dat_table_nas)
```


```{r}
dat_selection <- dat_table_nas %>% filter(percentage_na < .8)
nrow(dat_selection)

dat_selection %>% filter(percentage_na < .8) %>% reactable(.,filterable = T)
```

```{r}
str_subset(dat_selection$name,pattern = "p26")
```

i will group into logical, factor or numeric 

i will only mark things as logical or numeric 

```{r}
c(
  "p24_parentes","p25_sexo","p26_edad","")
```

```{r}
list_variables <- dat_selection$name

dat_ko_variables <- data_frame(
  "variable" = character(),
  "r_squared_num" = character(),
  "p_value_num" = character(),
  "r_squared_factor" = character(),
  "p_value_factor" = character(),
  "n_fac_lelves" = character(),
  "min" = character(),
  "qnt_1st" = character(),
  "median" = character(),
  "mean" = character(),
  "qnt_3rd" = character(),
  "max" = character(),
  "NA_percentage" = character()
)

for (i in 1:length(list_variables)) {
  tmp_object <- list_variables[i]
  tmp_variable_num <- sample[[tmp_object]]
  tmp_variable_fac <- tmp_variable_num %>% as.factor()
  tmp_length_variable <- table(tmp_variable_fac) %>% length()
  
  print(paste0("now doing number: ", i))
  
  ### dont run model if more then 15 factor
  if (tmp_length_variable > 15) {
    tmp_data <- data_frame(
      "variable" = tmp_object,
      "r_squared_num" = NA,
      "p_value_num" = NA,
      "r_squared_factor" = NA,
      "p_value_factor" = NA,
      "n_fac_lelves" = tmp_length_variable,
      "min" = summary(tmp_variable_num)[1],
      "qnt_1st" = summary(tmp_variable_num)[2],
      "median" = summary(tmp_variable_num)[3],
      "mean" = summary(tmp_variable_num)[4],
      "qnt_3rd" = summary(tmp_variable_num)[5],
      "max" = summary(tmp_variable_num)[6],
      "NA_percentage" = mean(is.na(tmp_variable_num))
    )
    
    dat_ko_variables <- rbind(dat_ko_variables, tmp_data)
    print("early exit, too many")
    next
    
  } else if (tmp_length_variable <= 1) {
    tmp_data <- data_frame(
      "variable" = tmp_object,
      "r_squared_num" = NA,
      "p_value_num" = NA,
      "r_squared_factor" = NA,
      "p_value_factor" = NA,
      "n_fac_lelves" = tmp_length_variable,
      "min" = summary(tmp_variable_num)[1],
      "qnt_1st" = summary(tmp_variable_num)[2],
      "median" = summary(tmp_variable_num)[3],
      "mean" = summary(tmp_variable_num)[4],
      "qnt_3rd" = summary(tmp_variable_num)[5],
      "max" = summary(tmp_variable_num)[6],
      "NA_percentage" = mean(is.na(tmp_variable_num))
    )
    
    dat_ko_variables <- rbind(dat_ko_variables, tmp_data)
    print("early exit, one or less")
    next
    
  } else {
    formula <- as.formula(paste("aestudio ~", tmp_object))
    model_num <- lm(sample$aestudio ~ tmp_variable_num)
    model_fac <- lm(sample$aestudio ~ tmp_variable_fac)
    
    r_squared_num <- summary(model_num)$r.squared
    p_value_num <- summary(model_num)$coefficients[1, 4]
    
    r_squared_factor <- summary(model_fac)$r.squared
    p_value_factor <- summary(model_fac)$coefficients[1, 4]

    tmp_data <- data_frame(
      "variable" = tmp_object,
      "r_squared_num" = r_squared_num,
      "p_value_num" = p_value_num,
      "r_squared_factor" = r_squared_factor,
      "p_value_factor" = p_value_factor,
      "n_fac_lelves" = tmp_length_variable,
      "min" = summary(tmp_variable_num)[1],
      "qnt_1st" = summary(tmp_variable_num)[2],
      "median" = summary(tmp_variable_num)[3],
      "mean" = summary(tmp_variable_num)[4],
      "qnt_3rd" = summary(tmp_variable_num)[5],
      "max" = summary(tmp_variable_num)[6],
      "NA_percentage" = mean(is.na(tmp_variable_num))
    )
    dat_ko_variables <- rbind(dat_ko_variables, tmp_data)
  }
}

```

```{r}
options(scipen = 999)
dat_ko_variables[,-1] <- sapply(dat_ko_variables[,-1],FUN = function(x) round(as.numeric(x),5))

dat_ko_variables %>% reactable(.,compact = T, filterable = T)
```


```{r}
dat_ko_variables <- dat_ko_variables[dat_ko_variables$NA_percentage <.3,]
```

```{r}
dat_ko_variables_selection <- dat_ko_variables[order(dat_ko_variables$r_squared_factor,decreasing = T),]
```

```{r}
library(openxlsx)
write.xlsx(dat_ko_variables_selection,"../../data_raw/2024_census/processed/dat_ko_variables_selection.xlsx")
```


```{r}
candidates <- dat_ko_variables_selection[1:50,"variable"]
```

```{r}
sample_candidates <- sample[,candidates$variable]
formula <- paste("aestudio ~",paste(colnames(sample_candidates),collapse =  " + " ))
formula <- formula %>% as.formula()

sample_candidates$aestudio <- sample$aestudio

model <- lm(formula = formula,data = sample_candidates)

step(model,direction = "backward")


model_step <- lm(aestudio ~ p41a_nivel + p41a_nivel_act + nivel_edu + p41b_curso_act + 
    p41b_curso + ocu_1d_13 + p40_lee + gedadedu + g_edad_bol + 
    g_edad + p53_ecivil + p38_asiste + hh_v19c_compu + p42d_comuni + 
    hh_v10_combus + asiste + hh_v11_basura + p42_discap + p31_afiliado + 
    hh_v19e_inetfijo + p42a_ver + hh_v03_pared + hh_v19b_tv + 
    p43_pago + hh_v18f_refri + hh_v15_servsan + hh_v19h_d + p37_lugres5 + 
    hh_v19g_tvcable + p30b_caja + hh_v08_aguadist + hh_v17_tenencia + 
    idep + hh_v18c_auto + hh_v05_techo,data = sample)

model_step %>% summary()
```

```{r}
na_counts <- sapply(sample_candidates, function(x) sum(is.na(x)))
sort(na_counts, decreasing = TRUE)

```

```{r}
dat_ko_variables_selection_filled<- openxlsx::read.xlsx("../../data_raw/2024_census/processed/dat_ko_variables_selection_filled.xlsx")

dat_ko_variables_selection_filled <- dat_ko_variables_selection_filled %>%
    filter(include == "yes" | include == "decide")

sample_candidates <- sample[,dat_ko_variables_selection_filled$variable]
formula <- paste("aestudio ~",paste(colnames(sample_candidates),collapse =  " + " ))
formula <- formula %>% as.formula()

sample_candidates$aestudio <- sample$aestudio

model <- lm(formula = formula,data = sample_candidates)
#model %>% summary()

step(model,direction = "backward")

model_step <- lm(aestudio ~ p40_lee + gedadedu + g_edad_bol + g_edad + p42c_camina + 
    p53_ecivil + hh_v19c_compu + p42d_comuni + p50_catocu_13 + 
    p42b_oir + hh_v10_combus + hh_v06_piso + hh_v19e_f + hh_v11_basura + 
    p42_discap + p31_afiliado + hh_v19f_inetmovil + hh_v19e_inetfijo + 
    p42a_ver + hh_v03_pared + hh_v19b_tv + hh_v18j_lavadora + 
    hh_urbrur + p43_pago + hh_v18f_refri + hh_v15_servsan + hh_v19h_d + 
    hh_v19d_celular + hh_v19g_tvcable + hh_v08_aguadist + hh_v18g_micro + 
    hh_v17_tenencia + hh_v18c_auto + hh_v05_techo + p32_pueblo_per + 
    hh_v04_revoq + p35_lugnac + p30c_privad + p25_sexo + hh_v18b_moto + 
    hh_v18h_calefon + hh_v18i_aire + hh_v13_habitac + p30a_public + 
    p30d_atedom + hh_v19h_telfijo + hh_v18d_carreta,sample)

model_step %>% summary()

install.packages("mice")

library(mice)
library(VIM)

aggr(sample_candidates, numbers = TRUE, prop = TRUE)
imp <- mice(sample_candidates, m = 5, maxit = 10, seed = 123)
completed_data <- complete(imp, 1) 
plot(imp)

library(glmnet)
cv_lasso <- cv.glmnet(completed_data[,dat_ko_variables_selection_filled$variable]), sample$aestudio, alpha = 1, nfolds = 10)  # 10-fold CV

# Best lambda
best_lambda <- cv_lasso$lambda.min
best_lambda_1se <- cv_lasso$lambda.1se

# Plot cross-validation curve
plot(cv_lasso)

```




```{r}
lm(sample$aestudi ~ + sample$p26_edad + sample$p25_sexo) %>% summary

### plus occupancy
lm(sample$aestudi ~ sample$p26_edad + as.factor(sample$ocu_1d_13) + sample$p25_sexo) %>% summary


### plus rural/urban
lm(sample$aestudi ~ sample$p26_edad + as.factor(sample$ocu_1d_13) + sample$p25_sexo + sample$hh_urbrur) %>% summary

#### 
# sample$p43_pago + sample$hh_tot_pers 
lm(sample$aestudi ~ sample$p26_edad + as.factor(sample$ocu_1d_13) + sample$p25_sexo + sample$hh_urbrur + sample$p40_lee) %>% summary

```

```{r}
domain_cov_raw <- fread("../../data_raw/large_files/Persona_CPV-2024.csv")

### select only relevant variables 
domain_cov_raw <- domain_cov_raw %>% filter(p26_edad >= 18)

domain_cov_raw$matchingID <- paste0(
  sprintf("%02.0f", domain_cov_raw$idep),
  sprintf("%02.0f", domain_cov_raw$iprov),
  sprintf("%02.0f", domain_cov_raw$imun)) %>% as.numeric()

domain_cov_raw <- domain_cov_raw %>% select(matchingID,p25_sexo,p26_edad,p40_lee,ocu_1d_13)

domain_cov_raw <-  domain_cov_raw %>% mutate(
  p25_sexo_t = case_when(
    p25_sexo %in% 1 ~ 1, ### 1 is female
    p25_sexo %in% 2 ~ 0), ### 2 was and 0 ist male now 
  
  p40_lee_t = case_when(
    p40_lee %in% 1 ~ 1, ## 1 is knowing how to read
    p40_lee %in% 2 ~ 0), ## 2 was and 0 is not knowing how to read
  
  # hh_urb_t = case_when(
  #   p40_lee %in% 1 ~ 1, ## 1 is urban
  #   p40_lee %in% 2 ~ 0), ## 2 was and 0 is rural (not_urban)
  
  ocu_military = case_when(
    ocu_1d_13 %in% 0 ~ 1, 
    !(ocu_1d_13 %in% 0) ~ 0), 

  ocu_managers = case_when(
    ocu_1d_13 %in% 1 ~ 1, 
    !(ocu_1d_13 %in% 1) ~ 0), 
  
  ocu_professionals = case_when(
    ocu_1d_13 %in% 2 ~ 1, 
    !(ocu_1d_13 %in% 2) ~ 0), 
  
  ocu_technicians = case_when(
    ocu_1d_13 %in% 3 ~ 1, 
    !(ocu_1d_13 %in% 3) ~ 0), 
  
  ocu_adminSupport = case_when(
    ocu_1d_13 %in% 4 ~ 1, 
    !(ocu_1d_13 %in% 4) ~ 0), 

  ocu_serviceSales = case_when(
    ocu_1d_13 %in% 5 ~ 1, 
    !(ocu_1d_13 %in% 5) ~ 0), 
  
  ocu_agriculture = case_when(
    ocu_1d_13 %in% 6 ~ 1, 
    !(ocu_1d_13 %in% 6) ~ 0), 
  
  ocu_construction = case_when(
    ocu_1d_13 %in% 7 ~ 1, 
    !(ocu_1d_13 %in% 7) ~ 0), 

  ocu_operators = case_when(
    ocu_1d_13 %in% 8 ~ 1, 
    !(ocu_1d_13 %in% 8) ~ 0), 
  
  ocu_unskilled = case_when(
    ocu_1d_13 %in% 9 ~ 1, 
    !(ocu_1d_13 %in% 9) ~ 0), 
  
  ocu_incomplete = case_when(
    ocu_1d_13 %in% 97 ~ 1, 
    !(ocu_1d_13 %in% 97) ~ 0), 

  ocu_unspecified = case_when(
    ocu_1d_13 %in% 99 ~ 1, 
    !(ocu_1d_13 %in% 99) ~ 0)
)  

covariats_numeric <-  c("p26_edad")

### fast way tot get the ocu parts of the vector 
# grep(x = colnames(domain_cov_raw),pattern = "ocu_",value = T) %>% paste0('"', .,'"',collapse = ",") %>% cat
covariats_factors <- c("p25_sexo_t","p40_lee_t",
                       # "hh_urb_t",
                       "ocu_military","ocu_managers","ocu_professionals","ocu_technicians","ocu_adminSupport","ocu_serviceSales","ocu_agriculture","ocu_construction","ocu_operators","ocu_unskilled","ocu_incomplete","ocu_unspecified")


domain_cov_aux <- domain_cov_raw %>%
  mutate(matchingID = as.character(matchingID)) %>% 
  group_by(matchingID) %>%
  summarise(
    ### for the numeric covariats we will take the mean of the municipalities 
    across(all_of(covariats_numeric), ~ mean(.x, na.rm = TRUE), .names = "mean_{.col}"),
  
    ### the facotrs, we will take the share 
    across(all_of(covariats_factors), ~ mean(.x == 1, na.rm = TRUE), .names = "share_{.col}")
  ) %>%
  ungroup()

domain_sample <- sample %>%
  mutate(matchingID = as.character(matchingID)) %>% 
  group_by(matchingID) %>%
  summarise(
    Mean_aestudio = mean(aestudio, na.rm = TRUE),
    Var_aestudio  = var(aestudio, na.rm = TRUE)
  ) %>%
  ungroup()

str(domain_sample)
str(domain_cov_aux)

data_sae <- merge(domain_sample,domain_cov_aux, by = "matchingID")
data_sae_clean <- data_sae %>% as.data.frame()

fh_model_null <- fh(
  fixed = Mean_aestudio ~ 1,
  vardir = "Var_aestudio",
  combined_data = data_sae_clean,
  domains = "matchingID",
  method = "reml",
  MSE = T
)

fh_model_null$MSE$FH %>% mean()

fh_model <- fh(
  fixed = Mean_aestudio ~ mean_p26_edad + share_p25_sexo_t,
  vardir = "Var_aestudio",
  combined_data = data_sae_clean,
  domains = "matchingID",
  method = "reml",
  MSE = T
)

fh_model$MSE$FH %>% mean()


sigma_u2 <- 0.00005276053

# Sampling variances
Vi <- data_sae_clean$Var_aestudio

# Shrinkage factors
Bi <- Vi / (Vi + sigma_u2)

# Add to your data
data_sae_clean$Bi <- Bi

# Quick summary
summary(Bi)

```


```{r}
plot(domain_cov_clean$Mean_aestudio, fh_model$est$FH)
abline(0,1,col="red")

# fh_model <- fh(
#   fixed = Mean_aestudio ~ mean_p26_edad + share_p25_sexo_t + share_p40_lee_t +
#            share_hh_urb_t  + share_ocu_adminSupport +
#            share_ocu_serviceSales + share_ocu_agriculture + share_ocu_construction +
#            share_ocu_operators + share_ocu_unskilled + share_ocu_incomplete,
#   vardir = "Var_aestudio",       
#   combined_data = domain_cov_clean,    
#   domains = "matchingID",        
#   method = "reml",               
#   MSE = T                     
# )


#### deleting lee, because mabye perfectly correlates with ocupations
fh_model <- fh(
  fixed = Mean_aestudio ~ mean_p26_edad + share_p25_sexo_t  +
          # share_hh_urb_t  +
    share_ocu_adminSupport +
           share_ocu_serviceSales + share_ocu_agriculture + share_ocu_construction +
           share_ocu_operators + share_ocu_unskilled + share_ocu_incomplete,
  vardir = "Var_aestudio",
  combined_data = domain_cov_clean,
  domains = "matchingID",
  method = "reml",
  MSE = T
)

fh_model$MSE$FH %>% mean()

fh_model_null <- fh(
  fixed = Mean_aestudio ~ 1,
  vardir = "Var_aestudio",       
  combined_data = domain_cov_clean,    
  domains = "matchingID",        
  method = "reml",               
  MSE = T                    
)

fh_model_null$MSE$FH %>% mean()



min(domain_cov$Var_aestudio)

domain_cov %>% str()

any(is.na(domain_cov$Mean_aestudio))
any(is.na(domain_cov$matchingID))
length(unique(domain_cov$matchingID)) == nrow(domain_cov)

str(domain_cov)

str(domain_cov$Mean_aestudio)
any(is.na(domain_cov$Mean_aestudio))

sapply(domain_cov %>% select(starts_with("mean_"), starts_with("share_")), class)

domain_cov <- domain_cov %>%
  mutate(across(starts_with("mean_"), as.numeric),
         across(starts_with("share_"), as.numeric))

any(is.na(domain_cov$matchingID))
length(unique(domain_cov$matchingID)) == nrow(domain_cov)


domain_cov_clean <- domain_cov %>% select(matchingID,Mean_aestudio,Var_aestudio,mean_p26_edad,share_p25_sexo_t) %>% as.data.frame()

fh_model <- fh(
  fixed = Mean_aestudio ~ mean_p26_edad + share_p25_sexo_t,
  vardir = "Var_aestudio",
  combined_data = domain_cov_clean,
  domains = "matchingID",
  method = "reml",
  MSE = T
)

fh_model

```


