---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### packages
library(tidyverse)
library(reactable)
library(data.table)
```

# Introduction 
This script is used to create the samples that will be used in our simulation study. 

```{r}
dat <- readRDS("../../data_raw/large_files/dat_preprocessing-01.RDS")
```

# sample for model building 

## only using people with data in aestudio for sample 

I think for now we should only use people with a value in aestudio (our dependen variable).

```{r}
set.seed(420)
dat <- dat[!is.na(dat$aestudio),]

### first smaple for modeling
sample_model_building <- dat %>%
  group_by(ID_prov) %>%
  slice_sample(n = 20) %>%
  ungroup()

## save the sampling for model building
saveRDS(sample,"../../data_raw/samples/sample_for_model_building.RDS")
```


```{r}
#### smaples for simulation
n_size_simulation <- 200

for(i in 1:n_size_simulation){
tmp_sample <- dat %>%
  group_by(ID_prov) %>%
  slice_sample(n = 20) %>%
  ungroup()

  doc_name <- paste0("../../data_raw/samples/","sample_",sprintf("%03.0f",i),".RDS")
  saveRDS(tmp_sample,doc_name)
}

```
 
