---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduciton this script is used to make a good selection for a variable 

```{r}
library(data.table)
library(tidyverse)
head1000_houshold <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv", nrows = 10000)
dat_houshold_raw <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv")


dat_houshold_raw$pers_per_room <- dat_houshold_raw$v13_habitac / dat_houshold_raw$tot_pers 
summary(dat_houshold_raw$pers_per_room)

dat_houshold_raw$v13_habitac %>% summary()
hist(dat_houshold_raw$pers_per_room,breaks = 30)

table_freq <- table(dat_houshold_raw$pers_per_room %>% round(3)) %>% as.matrix() %>% as.data.frame()

table_freq$V1 %>% hist(.,breaks = 100)


table_freq %>% filter(V1 > 10000)
```
create miniciapl id 

```{r}
dat_houshold_raw$ADM3_PCODE <- paste0("BO",
  sprintf("%02d",dat_houshold_raw$idep),
  sprintf("%02d",dat_houshold_raw$iprov),
  sprintf("%02d",dat_houshold_raw$imun)
  )

dat <- dat_houshold_raw %>% group_by(ADM3_PCODE) %>% summarise(mean_pers_per_room = mean(pers_per_room, na.rm = T))
```

merge with map

```{r}
library(sf)
library(tidyverse)
map <- read_sf("../../data_raw/shape/bol_adm_mdrt_2013/bol_admbnd_adm3_mdrt_2013_v01.shp")

map <- merge(map,dat,by = "ADM3_PCODE")

ggplot(map) +
  geom_sf(aes(fill = mean_pers_per_room), color = "grey20", size = 0.1) +
  theme_classic()

```

## which other variables are failry 

```{r}
head1000_person <- fread("../../data_raw/large_files/Persona_CPV-2024.csv", nrows = 10000)
dat_person_raw <- fread("../../data_raw/large_files/Persona_CPV-2024.csv")


dat_person_raw$ADM3_PCODE <- paste0("BO",
  sprintf("%02d",dat_person_raw$idep),
  sprintf("%02d",dat_person_raw$iprov),
  sprintf("%02d",dat_person_raw$imun)
  )

dat <- dat_person_raw %>% group_by(ADM3_PCODE) %>% summarise(mean_years_of_education = mean(aestudio, na.rm = T))

map <- merge(map,dat,by = "ADM3_PCODE")

hist(dat_person_raw$aestudio)

ggplot(map) +
  geom_sf(aes(fill = mean_years_of_education), color = "grey20", size = 0.1) +
  theme_classic() +
  ggtitle("average years of education")


```

# houshold survey
```{r}

dat_housholdsurvey_person <- read_sav("../../data_raw/2021_houshold-survey/EH2021_Persona.sav")

dat_housholdsurvey_person$yhog %>% 
  hist(., 
       breaks = 100, 
       main = "Monthly Household Income", 
       xlab = "Income (Bs/Month)")

dat <- 

```



