---
title: "Template Title"
author: "Lorenz Alban Oehler"
date: "The Date"
output:
  html_document:
    theme: flatly      
    toc: true          
    toc_float: true    
    toc_depth: 4       
    highlight: tango   
    df_print: paged    
    css: styles.css 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
```

```{r}
library(haven)
library(tidyverse)
library(reactable)
library(sf)
library(data.table)

```


## load files 
```{r}
dat_person_raw <- fread("../../data_raw/large_files/Persona_CPV-2024.csv")
dat_houshold_raw <- fread("../../data_raw/large_files/Vivienda_CPV-2024.csv")
```

## create mathcing id 

```{r}
dat_person_raw$matchingID <- paste0(
  sprintf("%02.0f", dat_person_raw$idep),
  sprintf("%02.0f", dat_person_raw$iprov),
  sprintf("%02.0f", dat_person_raw$imun)) %>% as.numeric()

dat_houshold_raw$matchingID <- paste0(
  sprintf("%02.0f", dat_houshold_raw$idep),
  sprintf("%02.0f", dat_houshold_raw$iprov),
  sprintf("%02.0f", dat_houshold_raw$imun)) %>% as.numeric()

```

### create unique ID 

```{r}
dat_person_raw$ID <- paste0("per_",1:nrow(dat_person_raw))
dat_houshold_raw$ID <- paste0("hh_",1:nrow(dat_houshold_raw))
```


## seletion

```{r}
# dat_person_raw_archive <- dat_person_raw
# dat_person_raw <- dat_person_raw_archive
# dat_houshold_raw_archive <- dat_houshold_raw
# dat_houshold_raw <- dat_houshold_raw_archive
  
dat_person_raw <- dat_person_raw[,c("ID","matchingID","i00","p41a_nivel","nivel_edu","aestudio","p40_lee")]

dat_houshold_raw <- dat_houshold_raw[,c("ID","matchingID","i00","tot_pers","tip_hog")]

saveRDS(dat_person_raw,"../../data_raw/")
```

```{r}
str(dat_person_raw)
str(dat_houshold_raw)
```

```{r}
### for easier handling take only some part

```


## investigate properties of variables

```{r}
dat_person_raw$p41a_nivel %>% table() %>% as.matrix() %>% reactable(.,compact = T)


```



The idea of the index is to create a value per houshold which is nicer to handel and has nice statistical properties


how many of the persons have a matchin the houshold data?

```{r}
dat_person_raw$i00 %in% dat_houshold_raw$i00 %>% table()
```


```{r}
avg_edu_year <- dat_person_raw %>% group_by(i00) %>% summarise(mean_studyYears = mean(aestudio,na.rm = T))

avg_edu_year$mean_studyYears %>% as.numeric() %>% hist()
```


## shape file 

```{r}
library(sf)
map <- read_sf("../../data_raw/shape/bol_adm_mdrt_2013/bol_admbnd_adm3_mdrt_2013_v01.shp")

### create new matchin ID column,
map$matchingID <- str_remove(map$ADM3_PCODE,pattern = "BO")
map$matchingID <- map$matchingID %>% as.numeric()
```

### join map with data

```{r}
sample <- readRDS("../../data_raw/samples/sample_for_model_building.RDS")

tmp_dat <-  sample %>% group_by(matchingID) %>% summarise(mean_aestudio = mean(aestudio,na.rm = T))

map <- tmp_dat %>%
  left_join(map, by = "matchingID") %>% 
  st_as_sf() %>%  
  select(-geometry, geometry)

ggplot(map) +
  geom_sf(aes(fill = mean_aestudio), color = "grey20", size = 0.1) +
  theme_classic()
```

