---
title: "latex"
author: "Lorenz Oehler"
date: "2026-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("htmltools")
# install.packages("webshot2")
# install.packages("rsvg")
# install.packages("magick")
# install.packages("pdftools")
library(htmltools)
library(pdftools)
library(webshot2)
library(rsvg)
library(katex)
library(magick)

# Deine Formel
formula_latex <- "\\widehat{\\mathrm{Var}}(\\bar{y}_d) = (1 - n_d/N_d) \\frac{s_d^2}{n_d}"

html_svg <- katex_html(formula_latex, output = "svg")

# anzeigen (optional)
cat(html_svg)

writeLines(html_svg, "formula.svg")

```

# Introduction
In this document I want to creat SVGs with the formulas we are using for the poster
$\widehat{\mathrm{Var}}(\bar{y}_d) = (1 - n_d/N_d) \frac{s_d^2}{n_d}$

```{r}
formula_latex <- "$\\hat{\\mathrm{Var}}(\\bar{y}_d) = (1 - n_d/N_d) \\frac{s_d^2}{n_d}$"

#ormula <- "\\widehat{\\mathrm{Var}}(\\bar{y}_d) = (1 - n_d/N_d) \\frac{s_d^2}{n_d}"

# LaTeX-Dokument erstellen
tex_file <- "formula.tex"
cat(sprintf("\\documentclass[preview]{standalone}
\\usepackage{amsmath}
\\begin{document}
\\[%s\\]
\\end{document}", formula),
    file = tex_file)

system("pdflatex -interaction=nonstopmode formula.tex")



# PDF lesen
img <- image_read_pdf("formula.pdf", density = 300)


# Transparent machen (optional, für Poster)
img <- image_transparent(img, "white")

# Als PNG speichern
image_write(img, path = "formula.png")

# Als SVG speichern
# Hinweis: magick erzeugt PNG, für echtes SVG: pdftocairo -svg formula.pdf formula.svg
system("pdftocairo -svg formula.pdf formula.svg")

```

```{r}
library(katex)

# Deine Formel
formula_latex <- "\\hat{\\mathrm{Var}}(\\bar{y}_d) = (1 - n_d/N_d) \\frac{s_d^2}{n_d}"

# SVG-Code erzeugen
svg_code <- katex_html(formula_latex)

# SVG in Datei speichern
# Wichtig: use UTF-8 encoding
writeLines(svg_code, "formula.svg", useBytes = TRUE)
```


